blueprint:
  name: Morning Brief on Alexa (LLM + Fallback + Retries)
  description: >
    On a single helper toggle (e.g., Alexa Routine "Alarm dismissed"),
    fetch today's Google Calendar events (and optionally weather), shape a short briefing
    with an OpenAI Conversation agent (with retries/backoff), fall back to a simple
    formatter if needed, and speak it on selected Alexa device(s).
  domain: automation
  input:
    trigger_helper:
      name: Trigger helper (input_boolean exposed to Alexa)
      selector:
        entity:
          domain: input_boolean

    alexa_targets:
      name: Alexa device(s) to speak on
      description: One or more Echo devices from Alexa Media Player
      selector:
        entity:
          domain: media_player
          multiple: true

    calendars:
      name: Calendars to include
      selector:
        entity:
          domain: calendar
          multiple: true

    include_weather:
      name: Include weather
      description: Turn off to skip weather entirely
      default: true
      selector:
        boolean: {}

    weather_entity:
      name: Weather entity (used only if Include weather = on)
      selector:
        entity:
          domain: weather

    person_name:
      name: Person name (for personalization)
      default: ""
      selector:
        text:

    openai_agent:
      name: Conversation agent (OpenAI Conversation)
      description: Usually conversation.openai after adding the OpenAI Conversation integration
      default: conversation.openai
      selector:
        entity:
          domain: conversation

    speaking_style:
      name: Speaking style (prompt hint)
      default: "cheerful, concise, 20–30 seconds"
      selector:
        text:

    tts_mode:
      name: Alexa TTS mode
      description: "tts speaks immediately; announce plays a chime and can fan out"
      default: tts
      selector:
        select:
          options:
            - "tts"
            - "announce"

    max_events:
      name: Max events to include
      default: 12
      selector:
        number:
          min: 1
          max: 50
          step: 1
          mode: slider

    retry_attempts:
      name: LLM retry attempts
      description: Total tries (1 = no retry)
      default: 3
      selector:
        number:
          min: 1
          max: 5
          step: 1
          mode: slider

    retry_delay_ms:
      name: Base retry delay (ms)
      description: Exponential backoff uses base, base*2, base*4...
      default: 1200
      selector:
        number:
          min: 200
          max: 5000
          step: 100
          mode: slider

mode: single
max_exceeded: silent

variables:
  v_person: !input person_name
  v_style: !input speaking_style
  v_tts_mode: !input tts_mode
  v_max_events: !input max_events
  v_max_tries: !input retry_attempts
  v_base_delay_ms: !input retry_delay_ms
  v_include_weather: !input include_weather

trigger:
  - platform: state
    entity_id: !input trigger_helper
    from: "off"
    to: "on"

action:
  # 0) Today's window (inclusive start, exclusive end)
  - variables:
      start_dt: "{{ today_at('00:00:00') }}"
      end_dt:   "{{ as_datetime(as_timestamp(today_at('00:00:00')) + 86400) }}"

  # 1) Pull events from selected calendars
  - service: calendar.get_events
    target:
      entity_id: !input calendars
    data:
      start_date_time: "{{ start_dt }}"
      end_date_time: "{{ end_dt }}"
    response_variable: agenda

  # 2) (Optional) Weather
  - choose:
      - conditions: "{{ v_include_weather }}"
        sequence:
          - service: weather.get_forecasts
            target:
              entity_id: !input weather_entity
            data:
              type: daily
            response_variable: forecast
          - variables:
              weather_key: !input weather_entity
              today_forecast: >-
                {% set key = weather_key %}
                {% if forecast and forecast is mapping and (key in forecast)
                      and ('forecast' in forecast[key]) and (forecast[key]['forecast'] | count) > 0 %}
                  {{ forecast[key]['forecast'][0] }}
                {% else %}{}{% endif %}
    default:
      - variables:
          today_forecast: "{}"

  # 3) Flatten events safely (HA Jinja sandbox friendly)
  - variables:
      events_flat: >-
        {% set ns = namespace(items=[]) %}
        {% for cal in agenda %}
          {% set payload = agenda[cal] %}
          {% if payload is mapping and 'events' in payload %}
            {% for e in payload['events'] %}
              {% set s = e['start'] %}
              {% set en = e['end'] %}
              {% set s_is_date = (s is string and s | length == 10) %}
              {% set e_is_date = (en is string and en | length == 10) %}
              {% set all_day = s_is_date and e_is_date %}
              {% set sort_key = (s ~ 'T00:00:00') if all_day else s %}
              {% set ns.items = ns.items + [ {
                'calendar': cal,
                'summary': (e['summary'] if 'summary' in e else ''),
                'start': s,
                'end': en,
                'all_day': all_day,
                'sort_key': sort_key
              } ] %}
            {% endfor %}
          {% endif %}
        {% endfor %}
        {{ (ns.items | sort(attribute='sort_key'))[: (v_max_events | int)] }}

  # 4) Build the LLM prompt (don’t address by name if blank)
  - variables:
      llm_prompt: >-
        You are generating a short morning briefing to be spoken by Alexa{% if v_person|trim %} to {{ v_person }}{% endif %}.
        Use a friendly {{ v_style }} voice. Use British date/time conventions.
        Input data is JSON:
        {
          "date_iso": "{{ now().date().isoformat() }}",
          "events": {{ events_flat | tojson }},
          "weather_today": {{ today_forecast | tojson }}
        }
        Rules:
        - Start with weekday and date{{ ' and a one-line weather headline (temp highs/lows; mention rain chance if present)' if v_include_weather else '' }}.
        - If weather_today is empty, omit the weather entirely.
        - List key events in chronological order with clear times (e.g., "at 08:30, GCSE Physics revision; at 11:00, dentist").
        - For all-day multi-day events, say "(day X of N)" if the model can infer it; otherwise just say "(all day)".
        - If there are no events, say that explicitly and give a brief encouragement.
        - Keep to about 3–6 short sentences. No markup; plain text only.
        - If no name is provided, do not address the listener by name.

  # 5) LLM with retries + backoff
  - variables:
      speech_final: ""

  - repeat:
      until:
        - condition: template
          value_template: >-
            {{ (repeat.index >= (v_max_tries | int)) or ((speech_final | default('') | trim) != '') }}
      sequence:
        - service: conversation.process
          data:
            agent_id: !input openai_agent
            text: "{{ llm_prompt }}"
          response_variable: llm

        - variables:
            speech_try: >-
              {{ llm.response.speech.plain.speech
                 if llm is defined and llm.response is defined
                 and llm.response.speech is defined and llm.response.speech.plain is defined
                 else '' }}

        - choose:
            - conditions: "{{ speech_try | trim != '' }}"
              sequence:
                - variables:
                    speech_final: "{{ speech_try }}"
            - conditions: "{{ speech_try | trim == '' }}"
              sequence:
                - delay:
                    milliseconds: >-
                      {{ (v_base_delay_ms | int) * (2 ** (repeat.index - 1)) }}

  # 6) Non-LLM fallback (always available; greeting omits blank name)
  - variables:
      speech_basic: >-
        {% set parts = [] %}
        {% set greeting = 'Morning' ~ ( ' ' ~ v_person if v_person|trim else '' ) ~ '.' %}
        {% if v_include_weather and today_forecast %}
          {% set cond = today_forecast.condition | default('') %}
          {% set hi = today_forecast.temperature | default('?') %}
          {% set lo = today_forecast.templow | default('?') %}
          {% set parts = parts + [ greeting ~ ' Today: ' ~ cond ~ ', high ' ~ hi ~ '°, low ' ~ lo ~ '°.' ] %}
        {% else %}
          {% set parts = parts + [ greeting ] %}
        {% endif %}
        {% if events_flat | count == 0 %}
          {% set parts = parts + ['No events in the calendar. Have a great day!'] %}
        {% else %}
          {% set parts = parts + ['Here are your events:'] %}
          {% for e in events_flat %}
            {% if e.all_day %}
              {% set line = e.summary ~ ' (all day)' %}
            {% else %}
              {% set line = (e.start[11:16]) ~ ': ' ~ e.summary %}
            {% endif %}
            {% set parts = parts + [line] %}
          {% endfor %}
        {% endif %}
        {{ (parts | join(' '))[:790] }}

      speech: "{{ (speech_final | default('') | trim) if (speech_final | default('') | trim) != '' else speech_basic }}"

  # 7) Speak on Alexa (target INSIDE data)
  - service: notify.alexa_media
    data:
      target: !input alexa_targets
      message: "{{ speech[:790] }}"
      data:
        type: !input tts_mode

  # 8) Reset the helper
  - service: input_boolean.turn_off
    target:
      entity_id: !input trigger_helper
