blueprint:
  name: Morning Brief on Alexa (LLM + Fallback + Retries)
  description: >
    On a single helper toggle (e.g., from an Alexa Routine "Alarm dismissed"),
    fetch today's Google Calendar events and weather, shape into a short natural briefing
    with an OpenAI Conversation agent (with retries + backoff), fall back to a simple
    formatter if the call fails, and speak it on the selected Alexa device(s).
  domain: automation
  input:
    trigger_helper:
      name: Trigger helper (input_boolean exposed to Alexa)
      selector:
        entity:
          domain: input_boolean

    alexa_targets:
      name: Alexa device(s) to speak on
      description: One or more Echo devices from Alexa Media Player
      selector:
        entity:
          domain: media_player
          multiple: true

    calendars:
      name: Calendars to include
      selector:
        entity:
          domain: calendar
          multiple: true

    weather_entity:
      name: Weather entity
      selector:
        entity:
          domain: weather

    person_name:
      name: Person name (for personalization)
      default: "there"
      selector:
        text:

    openai_agent:
      name: Conversation agent (OpenAI Conversation)
      description: Usually 'conversation.openai' after you add the OpenAI Conversation integration.
      default: conversation.openai
      selector:
        entity:
          domain: conversation

    speaking_style:
      name: Speaking style (prompt hint)
      default: "cheerful, concise, 20–30 seconds"
      selector:
        text:

    tts_mode:
      name: Alexa TTS mode
      description: "'tts' speaks immediately; 'announce' plays a chime and can fan out"
      default: tts
      selector:
        select:
