blueprint:
  name: Better Thermostat Scheduler (Smart Guard)
  domain: automation
  description: |-
    Switches Better Thermostat between comfort and eco temperatures.
    
    GUARD LOGIC:
    This allows you to block heating (force Eco) based on any condition.
    Enter the logic as a Jinja2 Expression WITHOUT curly braces.
    
    Correct:  is_state('binary_sensor.door', 'off')
    Wrong:   {{ is_state('binary_sensor.door', 'off') }}

  source_url: https://github.com/t-d-d/ha-blueprints/blob/master/bt-scheduler.yaml

  input:
    target_bt:
      name: Better Thermostats
      selector:
        target:
          device:
            integration: better_thermostat
          entity:
            integration: better_thermostat
            domain: climate

    target_temperature:
      name: Eco Temperature
      default: 17
      selector:
        number:
          min: 5
          max: 35
          unit_of_measurement: °C

    schedule_for_bt_on:
      name: Schedule
      selector:
        entity:
          domain: schedule

    monitor_person:
      name: Persons
      default: []
      selector:
        entity:
          domain: person
          multiple: true

    monitor_zones:
      name: Zones
      default: []
      selector:
        entity:
          domain: zone
          multiple: true

    blocking_expression:
      name: Guard Expression
      description: >
        Return TRUE to block heating. 
        IMPORTANT: Do NOT use {{ }} curly braces.
        Example: is_state('binary_sensor.lounge_door', 'off')
      default: "false"
      selector:
        text:
          multiline: true

trigger:
  - platform: state
    entity_id: !input schedule_for_bt_on
  - platform: state
    entity_id: !input monitor_person
  
  # Trigger 1: Guard turns ON (e.g. Door closes)
  - platform: template
    value_template: "{{ !input blocking_expression }}"
    
  # Trigger 2: Guard turns OFF (e.g. Door opens)
  # Because the input has no braces, we can safely wrap it in 'not()'
  - platform: template
    value_template: "{{ not ( !input blocking_expression ) }}"

variables:
  target_bt: !input target_bt
  target_temperature: !input target_temperature
  schedule_for_bt_on: !input schedule_for_bt_on
  monitor_person: !input monitor_person
  monitor_zones: !input monitor_zones
  
  # We wrap the input in braces here so we can use the result in logic
  isBlocked: "{{ !input blocking_expression }}"
  isScheduled: "{{ is_state(schedule_for_bt_on, 'on') }}"
  
  zones: "{{ monitor_zones | map('state_attr', 'friendly_name') | list }}"
  numPeople: "{{ monitor_person | list | length }}"
  numPeopleAtHome: >-
    {% set data = namespace(count=0) %}
    {% for person in monitor_person %}
      {% if states(person) in (zones + ['home']) %}
        {% set data.count = data.count + 1 %}
      {% endif %}
    {% endfor %}
    {{ data.count }}

actions:
  - choose:
      # PRIORITY 1: Force Eco 
      # (Guard is True OR Schedule Off OR Away)
      - conditions: >-
          {{ isBlocked or not isScheduled or (numPeople > 0 and numPeopleAtHome == 0) }}
        sequence:
          - service: better_thermostat.set_temp_target_temperature
            data:
              temperature: !input target_temperature
            target: !input target_bt

      # PRIORITY 2: Restore Comfort 
      # (Guard is False AND Schedule On AND Home)
      - conditions: >-
          {{ not isBlocked and isScheduled and (numPeople == 0 or numPeopleAtHome > 0) }}
        sequence:
          - service: better_thermostat.restore_saved_target_temperature
            data: {}
            target: !input target_bt
