blueprint:
  name: Better Thermostat - Single Shot Edition
  domain: automation
  description: |-
    Advanced control for Better Thermostat (v1.8+).
    Calculates the target preset in variables and sends a single command.

    LOGIC PRIORITY:
    1. Smart Override (User Template)
    2. Away Matrix (Schedule On/Off)
    3. Home Matrix (Schedule On/Off)

  source_url: https://github.com/t-d-d/ha-blueprints/blob/master/bt-scheduler-single.yaml

  input:
    target_bt:
      name: Better Thermostat Entity
      selector: { entity: { domain: climate, integration: better_thermostat } }

    schedule_entity:
      name: Schedule (Awake Hours)
      selector: { entity: { domain: schedule } }

    monitor_person:
      name: Occupancy
      selector: { entity: { domain: person, multiple: true } }

    # --- MATRIX INPUTS ---
    preset_home_sched:
      name: ðŸ  Home + Active
      default: 'home'
      selector: &p_select { select: { options: [home, comfort, active, boost, sleep, eco, away, 'off'], custom_value: true } }

    preset_home_sleep:
      name: ðŸ  Home + Sleep
      default: 'sleep'
      selector: *p_select

    preset_away_sched:
      name: ðŸš² Away + Active (Pre-heat)
      default: 'eco'
      selector: *p_select

    preset_away_sleep:
      name: ðŸš² Away + Sleep
      default: 'away'
      selector: *p_select

    # --- OVERRIDE ---
    override_template:
      name: Smart Override Logic
      description: >
        Return a preset name to force it. Return False/None to skip.
        Context: is_scheduled, is_someone_home
      default: "{{ false }}"
      selector: { template: {} }

    preset_override_default:
      name: Default Override Preset
      description: Used if logic returns simple 'True'.
      default: 'boost'
      selector: *p_select

trigger:
  - platform: state
    entity_id: !input schedule_entity
  - platform: state
    entity_id: !input monitor_person
  - platform: time_pattern
    minutes: "/5"

variables:
  # 1. Inputs
  schedule_entity: !input schedule_entity
  monitor_person: !input monitor_person
  p_home_sched: !input preset_home_sched
  p_home_sleep: !input preset_home_sleep
  p_away_sched: !input preset_away_sched
  p_away_sleep: !input preset_away_sleep
  p_over_def: !input preset_override_default
  
  # 2. Context Helpers (Available to user template)
  is_scheduled: "{{ is_state(schedule_entity, 'on') }}"
  is_someone_home: >-
    {{ expand(monitor_person) | selectattr('state','in',['home','on']) | list | count > 0 }}

  # 3. Evaluate Override
  raw_override: !input override_template
  
  # 4. THE DECISION ENGINE
  # This single variable determines the outcome.
  final_preset: >-
    {# --- CHECK OVERRIDE FIRST --- #}
    {% if raw_override in [true, 'True', 'on'] %}
      {{ p_over_def }}
    {% elif raw_override not in [false, 'False', 'off', '', none] %}
      {{ raw_override }}
    
    {# --- CHECK AWAY MATRIX --- #}
    {% elif not is_someone_home %}
      {{ p_away_sched if is_scheduled else p_away_sleep }}
      
    {# --- DEFAULT TO HOME MATRIX --- #}
    {% else %}
      {{ p_home_sched if is_scheduled else p_home_sleep }}
    {% endif %}

action:
  # Check if we actually have a valid preset string to send
  - condition: template
    value_template: "{{ final_preset not in [none, '', 'None'] }}"
    
  - service: climate.set_preset_mode
    target:
      entity_id: !input target_bt
    data:
      preset_mode: "{{ final_preset }}"
