blueprint:
  name: Hybrid Presence
  description: >
    The ultimate tracker.
    
    1. Multiple SSIDs: Supports list of home networks.
    2. Alien WiFi: Connecting to a non-home WiFi triggers INSTANT Away.
    3. WiFi State Guard: If you toggle WiFi off manually, the disconnect is IGNORED.
    4. Grace Period: Protects against router reboots.
    5. Battery Guard: Protects against dead phones.
    
    REQUIRED: Companion App with 'WiFi Connection' AND 'WiFi State' sensors enabled.
  domain: automation
  input:
    gps_tracker:
      name: Companion App Tracker
      selector:
        entity:
          domain: device_tracker
          integration: mobile_app
    wifi_sensor:
      name: WiFi Connection Sensor (SSID)
      selector:
        entity:
          domain: sensor
          integration: mobile_app
    wifi_state:
      name: WiFi State Sensor (Enabled/Disabled)
      description: The sensor that reports if WiFi is on or off (e.g. sensor.pixel_wifi_state).
      selector:
        entity:
          domain: sensor
          integration: mobile_app
    home_ssids:
      name: Home SSIDs
      description: Comma-separated list (e.g. MyHome, MyHome_5G).
      selector:
        text:
    person_id:
      name: Person ID
      default: user_1
    grace_period:
      name: Away Grace Period (Seconds)
      default: 120
      selector:
        number:
          min: 0
          max: 600
          unit_of_measurement: seconds

# ----------------------------------------------------------------
# AUTOMATION CONFIGURATION
# ----------------------------------------------------------------
mode: restart
max_exceeded: silent

trigger:
  - platform: state
    entity_id: !input gps_tracker
  - platform: state
    entity_id: !input wifi_sensor
  - platform: state
    entity_id: !input wifi_state
  - platform: homeassistant
    event: start

variables:
  gps_entity: !input gps_tracker
  wifi_entity: !input wifi_sensor
  wifi_state_entity: !input wifi_state
  
  ssid_input: !input home_ssids
  home_ssid_list: >
    {{ ssid_input.split(',') | map('trim') | list }}
  
  user_id: !input person_id
  new_tracker_id: "{{ user_id | slugify }}_hybrid"
  grace_sec: !input grace_period
  
  # LIVE STATES
  current_ssid: "{{ states(wifi_entity) | default('unknown') }}"
  # Check if WiFi radio is explicitly disabled/off
  radio_off: >
    {{ states(wifi_state_entity) in ['Disabled', 'disabled', 'off', 'Off'] }}
    
  wifi_connected_state: "<not connected>" 
  
  # TIMESTAMPS
  wifi_time: "{{ as_timestamp(states[wifi_entity].last_changed) | default(0) }}"
  gps_time: "{{ as_timestamp(states[gps_entity].last_updated) | default(0) }}"

  # DATA SNAPSHOT
  gps_lat: "{{ state_attr(gps_entity, 'latitude') | default(0) }}"
  gps_long: "{{ state_attr(gps_entity, 'longitude') | default(0) }}"
  batt: "{{ state_attr(gps_entity, 'battery_level') | int(default=0) }}"
  gps_acc: "{{ state_attr(gps_entity, 'gps_accuracy') | int(default=0) }}"
  
  home_lat: "{{ state_attr('zone.home', 'latitude') }}"
  home_long: "{{ state_attr('zone.home', 'longitude') }}"

action:
  - choose:
      # ----------------------------------------------------------------
      # SCENARIO 1: CONNECTED TO HOME SSID (Any of them)
      # Action: Force Home + Snap to Zone Center
      # ----------------------------------------------------------------
      - conditions:
          - condition: template
            value_template: "{{ current_ssid in home_ssid_list }}"
        sequence:
          - service: device_tracker.see
            data:
              dev_id: "{{ new_tracker_id }}"
              location_name: home
              source_type: router
              gps: ["{{ home_lat }}", "{{ home_long }}"]
              gps_accuracy: 10

      # ----------------------------------------------------------------
      # SCENARIO 2: CONNECTED TO ALIEN WIFI (Office, Starbucks)
      # Action: Force Away INSTANTLY
      # ----------------------------------------------------------------
      - conditions:
          - condition: template
            value_template: >
              {{ current_ssid != wifi_connected_state 
                 and current_ssid not in home_ssid_list 
                 and current_ssid != 'unknown' 
                 and current_ssid != 'unavailable' }}
        sequence:
          - service: device_tracker.see
            data:
              dev_id: "{{ new_tracker_id }}"
              location_name: not_home
              source_type: router
              gps: ["{{ gps_lat }}", "{{ gps_long }}"]
              gps_accuracy: "{{ gps_acc }}"

      # ----------------------------------------------------------------
      # SCENARIO 3: DISCONNECTED (Potential Leaving / Reboot / Sleep / Toggle)
      # ----------------------------------------------------------------
      - conditions:
          - condition: template
            value_template: "{{ states(gps_entity) == 'home' }}"
        sequence:
          - choose:
              # A. WiFi dropped RECENTLY -> Check Guards & Wait Grace Period
              - conditions:
                  - condition: template
                    value_template: "{{ wifi_time > gps_time }}"
                sequence:
                  # GUARD 1: WiFi Radio Manually Disabled? -> IGNORE.
                  - if:
                      - condition: template
                        value_template: "{{ radio_off }}"
                    then:
                      - stop: "WiFi manually disabled. Ignoring disconnect."

                  # GUARD 2: Battery Critical? -> Assume Dead Phone (Stay Home)
                  - if:
                      - condition: template
                        value_template: "{{ batt < 5 }}"
                    then:
                      - stop: "Phone battery critical. Assuming dead phone."
                  
                  # Grace Period: Wait for router reboot
                  - delay: "{{ grace_sec }}"
                  
                  # Re-Check: Still disconnected?
                  - if:
                      - condition: template
                        value_template: "{{ states(wifi_entity) not in home_ssid_list }}"
                    then:
                      - service: device_tracker.see
                        data:
                          dev_id: "{{ new_tracker_id }}"
                          location_name: not_home
                          source_type: router
                          gps: ["{{ gps_lat }}", "{{ gps_long }}"]
                          gps_accuracy: "{{ gps_acc }}"

              # B. GPS updated RECENTLY (Sleeping at Home) -> Force Home
              - conditions:
                  - condition: template
                    value_template: "{{ gps_time > wifi_time }}"
                sequence:
                  - service: device_tracker.see
                    data:
                      dev_id: "{{ new_tracker_id }}"
                      location_name: home
                      source_type: gps
                      gps: ["{{ gps_lat }}", "{{ gps_long }}"]
                      gps_accuracy: "{{ gps_acc }}"

    # ----------------------------------------------------------------
    # SCENARIO 4: GPS SAYS AWAY (Pass-through)
    # ----------------------------------------------------------------
    default:
      - service: device_tracker.see
        data:
          dev_id: "{{ new_tracker_id }}"
          location_name: "{{ states(gps_entity) }}"
          source_type: gps
          gps: ["{{ gps_lat }}", "{{ gps_long }}"]
          gps_accuracy: "{{ gps_acc }}"
