blueprint:
  name: WiFi-Anchored Presence
  description: >
    The definitive presence tracker (Simplified).
    
    1. ANCHORS you to 'Home' when WiFi is connected.
    2. RELEASES you to GPS when you leave.
    3. AUTO-DETECTS Battery and WiFi State sensors (based on Tracker name).
    4. AUTO-NAMES the new tracker (e.g. device_tracker.pixel_7_anchor).
    
    REQUIRED: Companion App with 'WiFi Connection' sensor enabled.
  domain: automation
  input:
    gps_tracker:
      name: Companion App Tracker
      description: The main GPS entity (e.g. device_tracker.pixel_7).
      selector:
        entity:
          domain: device_tracker
          integration: mobile_app
    wifi_sensor:
      name: WiFi Connection Sensor (SSID)
      description: >
        Must be selected manually to handle 'wifi' vs 'wi_fi' naming variations.
        Android: 'sensor.[name]_wifi_connection'
      selector:
        entity:
          domain: sensor
          integration: mobile_app
    home_ssids:
      name: Home SSIDs
      description: Comma-separated list of your home networks.
      selector:
        text:
    grace_period:
      name: Away Grace Period (Seconds)
      description: Wait time before marking Away if WiFi drops.
      default: 120
      selector:
        number:
          min: 0
          max: 600
          unit_of_measurement: seconds

# ----------------------------------------------------------------
# AUTOMATION CONFIGURATION
# ----------------------------------------------------------------
mode: restart
max_exceeded: silent

trigger:
  # 1. Standard: State changes (Must be explicit)
  - platform: state
    entity_id: !input gps_tracker
  - platform: state
    entity_id: !input wifi_sensor
  # 2. Maintenance: System startup
  - platform: homeassistant
    event: start
  # 3. Setup: Run immediately when ANY automation is saved/reloaded
  - platform: event
    event_type: automation_reloaded

variables:
  gps_entity: !input gps_tracker
  wifi_entity: !input wifi_sensor
  
  ssid_input: !input home_ssids
  home_ssid_list: >
    {{ ssid_input.split(',') | map('trim') | list }}
  
  # -----------------------------------------------------------
  # AUTO-DISCOVERY LOGIC
  # 1. Extract base name: device_tracker.nokia_g21 -> nokia_g21
  # 2. Construct sensor names dynamically.
  # -----------------------------------------------------------
  base_name: "{{ gps_entity.split('.')[1] }}"
  new_tracker_id: "{{ base_name }}_anchor"
  
  # We guess the entity IDs.
  # If your device is named 'nokia_g21', we look for:
  # sensor.nokia_g21_battery_level
  # binary_sensor.nokia_g21_wifi_state
  batt_entity_id: "sensor.{{ base_name }}_battery_level"
  wifi_state_entity_id: "binary_sensor.{{ base_name }}_wifi_state"

  grace_sec: !input grace_period
  
  # LIVE STATES
  current_ssid: "{{ states(wifi_entity) | default('unknown') }}"
  
  # -----------------------------------------------------------
  # SENSOR CHECKING (Fail-Safe)
  # -----------------------------------------------------------
  
  # WIFI STATE (Android Only)
  # Check if the guessed entity actually exists and is 'off'
  radio_off: >
    {% if states(wifi_state_entity_id) == 'off' %}
      true
    {% else %}
      false
    {% endif %}

  # BATTERY CHECK
  # If the guessed sensor is unknown/missing, default to 100 (Safe).
  batt_level: >
    {{ states(batt_entity_id) | int(default=100) }}
    
  # TIMESTAMPS
  wifi_time: "{{ as_timestamp(states[wifi_entity].last_changed) | default(0) }}"
  gps_time: "{{ as_timestamp(states[gps_entity].last_updated) | default(0) }}"

  # DATA SNAPSHOT
  gps_lat: "{{ state_attr(gps_entity, 'latitude') | default(0) }}"
  gps_long: "{{ state_attr(gps_entity, 'longitude') | default(0) }}"
  gps_acc: "{{ state_attr(gps_entity, 'gps_accuracy') | int(default=0) }}"
  
  home_lat: "{{ state_attr('zone.home', 'latitude') }}"
  home_long: "{{ state_attr('zone.home', 'longitude') }}"

action:
  - choose:
      # ----------------------------------------------------------------
      # SCENARIO 1: ANCHORED HOME (WiFi Connected)
      # ----------------------------------------------------------------
      - conditions:
          - condition: template
            value_template: "{{ current_ssid in home_ssid_list }}"
        sequence:
          - service: device_tracker.see
            data:
              dev_id: "{{ new_tracker_id }}"
              location_name: home
              source_type: router
              gps: ["{{ home_lat }}", "{{ home_long }}"]
              gps_accuracy: 10

      # ----------------------------------------------------------------
      # SCENARIO 2: ALIEN NETWORK (Instant Away)
      # ----------------------------------------------------------------
      - conditions:
          - condition: template
            value_template: >
              {{ current_ssid not in home_ssid_list 
                 and current_ssid != 'unknown' 
                 and current_ssid != 'unavailable'
                 and current_ssid != '<not connected>'
                 and current_ssid != 'Not Connected' }}
        sequence:
          - service: device_tracker.see
            data:
              dev_id: "{{ new_tracker_id }}"
              location_name: not_home
              source_type: router
              gps: ["{{ gps_lat }}", "{{ gps_long }}"]
              gps_accuracy: "{{ gps_acc }}"

      # ----------------------------------------------------------------
      # SCENARIO 3: DISCONNECTED (Check Guards)
      # ----------------------------------------------------------------
      - conditions:
          - condition: template
            value_template: "{{ states(gps_entity) == 'home' }}"
        sequence:
          - choose:
              # A. WiFi dropped RECENTLY -> Check Guards & Wait
              - conditions:
                  - condition: template
                    value_template: "{{ wifi_time > gps_time }}"
                sequence:
                  # GUARD: Manual Toggle (Auto-Detected)
                  - if:
                      - condition: template
                        value_template: "{{ radio_off }}"
                    then:
                      - stop: "WiFi manually disabled. Staying Anchored."

                  # GUARD: Dead Battery (Auto-Detected)
                  # If sensor was not found, batt_level is 100, so this check safely fails.
                  - if:
                      - condition: template
                        value_template: "{{ batt_level < 5 }}"
                    then:
                      - stop: "Battery critical. Staying Anchored."
                  
                  # Grace Period (Router Reboot Protection)
                  - delay: "{{ grace_sec }}"
                  
                  # Re-Check
                  - if:
                      - condition: template
                        value_template: "{{ states(wifi_entity) not in home_ssid_list }}"
                    then:
                      - service: device_tracker.see
                        data:
                          dev_id: "{{ new_tracker_id }}"
                          location_name: not_home
                          source_type: router
                          gps: ["{{ gps_lat }}", "{{ gps_long }}"]
                          gps_accuracy: "{{ gps_acc }}"

              # B. GPS updated RECENTLY -> Trust GPS
              - conditions:
                  - condition: template
                    value_template: "{{ gps_time > wifi_time }}"
                sequence:
                  - service: device_tracker.see
                    data:
                      dev_id: "{{ new_tracker_id }}"
                      location_name: home
                      source_type: gps
                      gps: ["{{ gps_lat }}", "{{ gps_long }}"]
                      gps_accuracy: "{{ gps_acc }}"

    # ----------------------------------------------------------------
    # SCENARIO 4: GPS SAYS AWAY (Pass-through)
    # ----------------------------------------------------------------
    default:
      - service: device_tracker.see
        data:
          dev_id: "{{ new_tracker_id }}"
          location_name: "{{ states(gps_entity) }}"
          source_type: gps
          gps: ["{{ gps_lat }}", "{{ gps_long }}"]
          gps_accuracy: "{{ gps_acc }}"
